### ISSUE TITLE
Terminal class

### ISSUE THREAD

**Issue by Sweet4ever** [Sweet4ever/Java-verktyg-gruppprojekt#1]
*DoD*:
Strukturera upp en meny som inte lämnas föränn exit numret ges.

Följande funktioner skapas lokalt i klassen
Print menu
Exit menu:

I menyn ska det gå att tillkalla funktionerna:
Lista
Sök
Lägg till
Ta bort
Exit

Exit menu ska spara undan 

Automatisk testfunktion av alla metoder.

**Comment by John-Rotte** [comment]
Strukturera upp en meny som inte lämnas föränn exit numret ges.

**I menyn ska det finnas funktionerna:**
Lista
Sök
Lägg till
Ta bort
Exit

Automatisk testfunktion av alla metoder.
